[wiki]
authors = ["Zhuang Biaowei"]
language = "zh"
src = "src"
title = "Open Source Markdown Wiki"

[preprocessor.citation]
command = "ruby citation.rb"

[citation]
zbw = {repo = "https://github.com/zhuangbiaowei/wiki.md", branch = "main", ref = ""}
